

export const LOGIN_OK="LOGIN_OK";
export const LOGIN_BAD="LOGIN_BAD";
export const LOGOUT="LOGOUT";
export const LOGIN="LOGIN";
export const REGISTER="REGISTER";
export const REGISTER_OK="REGISTER_OK";
export const REGISTER_BAD="REGISTER_BAD";
export const MOVIES_FETCH="MOVIES_FETCH";
export const MOVIES_FETCH_OK="MOVIES_FETCH_OK";
export const MOVIES_FETCH_BAD="MOVIES_FETCH_BAD";
export const SORT="SORT";
export const REVERSE="REVERSE";
export const MOVIES_SEARCH="MOVIES_SEARCH";
export const MOVIES_SEARCH_FETCH_BAD="MOVIES_SEARCH_FETCH_BAD";
export const MOVIES_SEARCH_FETCH_OK="MOVIES_SEARCH_FETCH_OK";
export const WANTED_MOVIES_FETCH_OK="WANTED_MOVIES_FETCH_OK";
export const WANTED_MOVIES_FETCH_BAD="WANTED_MOVIES_FETCH_BAD";
export const WANTED_MOVIES="WANTED_MOVIES";
export const IMAGES_FETCH="IMAGES_FETCH";
export const IMAGES_FETCH_OK="IMAGES_FETCH_OK";
export const IMAGES_FETCH_BAD="IMAGES_FETCH_BAD";
